defaults:
  - files: mnist
  - _self_
paths:
  log: ${hydra:runtime.cwd}/logs
  data: ${hydra:runtime.cwd}/data/raw
params:
  epoch_count: 20
  lr: 5e-5
  batch_size: 128
  shuffle: True
  num_workers: 2
checkpoint:
  save_interval: 5
  resume: False
  checkpoint_id: MnistModel-14_01_2022_00_14_27-10-0.90.pt.zip
  path: ${hydra:runtime.cwd}/checkpoints
