defaults:
  - files: mnist
  - _self_
paths:
  log: ${hydra:runtime.cwd}/logs
  data: ${hydra:runtime.cwd}/data/raw
params:
  epoch_count: 20
  lr: 5e-5
  batch_size: 128
  shuffle: True
  num_workers: 2
checkpoint:
  save_interval: 10
  resume: True
  checkpoint_id: MnistModel-13_01_2022_02_55_19-0-0.284.pth.zip
  path: ${hydra:runtime.cwd}/checkpoints
